# Generated by Django 5.2.15 on 2026-06-23 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_userprofile_delete_customuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomesticTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("beneficiary_name", models.CharField(max_length=150)),
                ("beneficiary_account_no", models.CharField(max_length=50)),
                ("bank_name", models.CharField(max_length=150)),
                ("account_type", models.CharField(blank=True, max_length=50)),
                ("narration", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domestic Transfer",
                "verbose_name_plural": "Domestic Transfers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WireTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("beneficiary_name", models.CharField(max_length=150)),
                ("beneficiary_account_no", models.CharField(max_length=50)),
                ("bank_name", models.CharField(max_length=150)),
                ("country", models.CharField(max_length=100)),
                ("swift_code", models.CharField(max_length=20)),
                ("routing_number", models.CharField(blank=True, max_length=50)),
                ("account_type", models.CharField(blank=True, max_length=50)),
                ("narration", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wire_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wire Transfer",
                "verbose_name_plural": "Wire Transfers",
                "ordering": ["-created_at"],
            },
        ),
    ]
