# Generated by Django 5.2.15 on 2026-06-23 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_domestictransfer_wiretransfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("Personal", "Personal Loan"),
                            ("Business", "Business Loan"),
                            ("Mortgage", "Mortgage Loan"),
                            ("Auto", "Auto Loan"),
                            ("Education", "Education Loan"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("duration_months", models.PositiveIntegerField()),
                ("purpose", models.TextField()),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Application",
                "ordering": ["-created_at"],
            },
        ),
    ]
