# Generated by Django 5.2.15 on 2026-06-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_deposit_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_image",
        ),
    ]
