# Generated by Django 5.2.15 on 2026-06-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_userprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="deposit_type",
            field=models.CharField(
                choices=[("Demand", "Demand Deposit"), ("Fixed", "Fixed Deposit")],
                max_length=10,
            ),
        ),
    ]
